package com.youyigejia.crm.mapper;

import com.youyigejia.crm.domain.BaseDict;

import java.util.List;

public interface BaseDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dict
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String dictId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dict
     *
     * @mbggenerated
     */
    int insert(BaseDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dict
     *
     * @mbggenerated
     */
    int insertSelective(BaseDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dict
     *
     * @mbggenerated
     */
    BaseDict selectByPrimaryKey(String dictId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dict
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BaseDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dict
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BaseDict record);

    List<BaseDict> searchByDictTypeCode(String dictTypeCode);
}