package com.youyigejia.crm.domain;

import java.util.Date;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_id
     *
     * @mbggenerated
     */
    private Long custId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_name
     *
     * @mbggenerated
     */
    private String custName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_user_id
     *
     * @mbggenerated
     */
    private Long custUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_create_id
     *
     * @mbggenerated
     */
    private Long custCreateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_source
     *
     * @mbggenerated
     */
    private String custSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_industry
     *
     * @mbggenerated
     */
    private String custIndustry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_level
     *
     * @mbggenerated
     */
    private String custLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_linkman
     *
     * @mbggenerated
     */
    private String custLinkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_phone
     *
     * @mbggenerated
     */
    private String custPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_mobile
     *
     * @mbggenerated
     */
    private String custMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_zipcode
     *
     * @mbggenerated
     */
    private String custZipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_address
     *
     * @mbggenerated
     */
    private String custAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_createtime
     *
     * @mbggenerated
     */
    private Date custCreatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_id
     *
     * @return the value of customer.cust_id
     *
     * @mbggenerated
     */
    public Long getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_id
     *
     * @param custId the value for customer.cust_id
     *
     * @mbggenerated
     */
    public void setCustId(Long custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_name
     *
     * @return the value of customer.cust_name
     *
     * @mbggenerated
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_name
     *
     * @param custName the value for customer.cust_name
     *
     * @mbggenerated
     */
    public void setCustName(String custName) {
        this.custName = custName == null ? null : custName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_user_id
     *
     * @return the value of customer.cust_user_id
     *
     * @mbggenerated
     */
    public Long getCustUserId() {
        return custUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_user_id
     *
     * @param custUserId the value for customer.cust_user_id
     *
     * @mbggenerated
     */
    public void setCustUserId(Long custUserId) {
        this.custUserId = custUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_create_id
     *
     * @return the value of customer.cust_create_id
     *
     * @mbggenerated
     */
    public Long getCustCreateId() {
        return custCreateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_create_id
     *
     * @param custCreateId the value for customer.cust_create_id
     *
     * @mbggenerated
     */
    public void setCustCreateId(Long custCreateId) {
        this.custCreateId = custCreateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_source
     *
     * @return the value of customer.cust_source
     *
     * @mbggenerated
     */
    public String getCustSource() {
        return custSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_source
     *
     * @param custSource the value for customer.cust_source
     *
     * @mbggenerated
     */
    public void setCustSource(String custSource) {
        this.custSource = custSource == null ? null : custSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_industry
     *
     * @return the value of customer.cust_industry
     *
     * @mbggenerated
     */
    public String getCustIndustry() {
        return custIndustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_industry
     *
     * @param custIndustry the value for customer.cust_industry
     *
     * @mbggenerated
     */
    public void setCustIndustry(String custIndustry) {
        this.custIndustry = custIndustry == null ? null : custIndustry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_level
     *
     * @return the value of customer.cust_level
     *
     * @mbggenerated
     */
    public String getCustLevel() {
        return custLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_level
     *
     * @param custLevel the value for customer.cust_level
     *
     * @mbggenerated
     */
    public void setCustLevel(String custLevel) {
        this.custLevel = custLevel == null ? null : custLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_linkman
     *
     * @return the value of customer.cust_linkman
     *
     * @mbggenerated
     */
    public String getCustLinkman() {
        return custLinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_linkman
     *
     * @param custLinkman the value for customer.cust_linkman
     *
     * @mbggenerated
     */
    public void setCustLinkman(String custLinkman) {
        this.custLinkman = custLinkman == null ? null : custLinkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_phone
     *
     * @return the value of customer.cust_phone
     *
     * @mbggenerated
     */
    public String getCustPhone() {
        return custPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_phone
     *
     * @param custPhone the value for customer.cust_phone
     *
     * @mbggenerated
     */
    public void setCustPhone(String custPhone) {
        this.custPhone = custPhone == null ? null : custPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_mobile
     *
     * @return the value of customer.cust_mobile
     *
     * @mbggenerated
     */
    public String getCustMobile() {
        return custMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_mobile
     *
     * @param custMobile the value for customer.cust_mobile
     *
     * @mbggenerated
     */
    public void setCustMobile(String custMobile) {
        this.custMobile = custMobile == null ? null : custMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_zipcode
     *
     * @return the value of customer.cust_zipcode
     *
     * @mbggenerated
     */
    public String getCustZipcode() {
        return custZipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_zipcode
     *
     * @param custZipcode the value for customer.cust_zipcode
     *
     * @mbggenerated
     */
    public void setCustZipcode(String custZipcode) {
        this.custZipcode = custZipcode == null ? null : custZipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_address
     *
     * @return the value of customer.cust_address
     *
     * @mbggenerated
     */
    public String getCustAddress() {
        return custAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_address
     *
     * @param custAddress the value for customer.cust_address
     *
     * @mbggenerated
     */
    public void setCustAddress(String custAddress) {
        this.custAddress = custAddress == null ? null : custAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_createtime
     *
     * @return the value of customer.cust_createtime
     *
     * @mbggenerated
     */
    public Date getCustCreatetime() {
        return custCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_createtime
     *
     * @param custCreatetime the value for customer.cust_createtime
     *
     * @mbggenerated
     */
    public void setCustCreatetime(Date custCreatetime) {
        this.custCreatetime = custCreatetime;
    }
}